services:
  tracks-service:
    image: tracks-api
    build:
      context: .
      dockerfile: Tracks/Tracks.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:7002
    ports:
      - "7002:7002"
    networks:
      - dev

  users-service:
    image: users-api
    build:
      context: .
      dockerfile: Users/Users.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:7001
    ports:
      - "7001:7001"
    networks:
      - dev

  gateway:
    image: gateway-api
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:7000
    depends_on:
      - tracks-service
      - users-service
    ports:
      - "7000:7000"
    networks:
      - dev

networks:
  dev:
    driver: bridge
